version: '3'

services:
  traefik:
    image: traefik:latest
    domain: upo.one
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - ./.htpasswd:/shared/.htpasswd
    labels:
      - "traefik.frontend.rule=Host:upo.one; PathPrefixStrip: /traefik"
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=web"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

networks:
  web:
    external: true