version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:upo.one"
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.backend=nginx"
      - "traefik.docker.network=web"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    restart: always

networks:
  web:
    external: true